### ISSUE TITLE
Versioned and unversioned W3C items: data differences & relationship errors

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-w3c#30] opened 2022-07-08 11:48 UTC
Compare these two:

- https://github.com/ietf-tools/relaton-data-w3c/tree/main/data/design-principles.yaml
- https://github.com/ietf-tools/relaton-data-w3c/tree/main/data/note-design-principles-20211216.yaml

I’m not sure what is the relationship, and why the first one has less data (e.g., no authors).

Is the first one an “umbrella” series item that includes the second item as just one version?

If authors differ from version to version, that would explain why the umbrella item doesn’t include authors. However, in that case we should probably have the relevant includedIn/includes relations specified.

**Comment by strogonoff** [comment] 2022-07-08 13:44
It seems like there are two possible concepts for unversioned ID:

1. Pointer to latest version (like a dynamic “symlink”?)
2. Container for all versions (we already have a precedent with Internet Drafts (unversioned I-D reference is a container for I-D versions)

I think it’s worth checking with @ronaldtse and maybe @opoudjis which approach makes more sense.

**Comment by ronaldtse** [comment] 2022-07-09 07:47
> Container for all versions (we already have a precedent with Internet Drafts (unversioned I-D reference is a container for I-D versions)

It is exactly the same. The semantic difference here is a "series" vs "item". "design-principles" is the work item, "design-principles-20211216" is the edition item.

The problem is I found inconsistencies with the data:

"design-principles" specified it has 1 edition:
https://github.com/ietf-tools/relaton-data-w3c/blob/0505298d4f9318eaa85516b3f97ee6d5fde8dcf9/data/design-principles.yaml#L20-L29

However, "design-principles-20211216" points to another "obsolete" item:
https://github.com/ietf-tools/relaton-data-w3c/blob/0505298d4f9318eaa85516b3f97ee6d5fde8dcf9/data/note-design-principles-20211216.yaml#L35-L44

Called "W3C NOTE-design-principles-20210923".

This means there are at least 2 items in "design-principles", but only 1 is shown.

Moreover, the doctype is wrong:
https://github.com/ietf-tools/relaton-data-w3c/blob/0505298d4f9318eaa85516b3f97ee6d5fde8dcf9/data/design-principles.yaml#L36

This is a NOTE, not a Recommendation.

Last but not least, "design-principles-20211216" says it has a "draft" called "design-principles":
https://github.com/ietf-tools/relaton-data-w3c/blob/0505298d4f9318eaa85516b3f97ee6d5fde8dcf9/data/note-design-principles-20211216.yaml#L45-L57

But it is incorrect -- the "design-principles" is not a draft of "design-principles-20211216". It is the parent container of it.

So I think we need to fix these data issues properly. Can you please help @andrew2net ?

**Comment by andrew2net** [comment] 2022-07-29 13:08
> However, "design-principles-20211216" points to another "obsolete" item:
> https://github.com/ietf-tools/relaton-data-w3c/blob/0505298d4f9318eaa85516b3f97ee6d5fde8dcf9/data/note-design-principles-20211216.yaml#L35-L44

@ronaldtse it points to the obsolete documents but the document doesn't exists in the `tr.rdf` file or W3C tr-archive

> Last but not least, "design-principles-20211216" says it has a "draft" called "design-principles": https://github.com/ietf-tools/relaton-data-w3c/blob/0505298d4f9318eaa85516b3f97ee6d5fde8dcf9/data/note-design-principles-20211216.yaml#L45-L57
> 
> But it is incorrect -- the "design-principles" is not a draft of "design-principles-20211216". It is the parent container of it.

The "draft" comes from the `ED` element:
```xml
<NOTE rdf:about="https://www.w3.org/TR/2021/NOTE-design-principles-20211216/">
  ...
  <ED rdf:resource="https://w3ctag.github.io/design-principles/"/>
</NOTE>
```
Nick called it "Editor's draft". Should we skip the `ED` element? May be handle it in other way?

**Comment by ronaldtse** [comment] 2022-07-30 07:04
> Nick called it "Editor's draft". Should we skip the ED element? May be handle it in other way?

Maybe this is the "Editor's Draft location", not a version of the draft.

**Comment by andrew2net** [comment] 2022-07-31 11:32
> Maybe this is the "Editor's Draft location", not a version of the draft.

@ronaldtse I have no idea how to treat the location, so if you also don't have then I'm going to skip it.

**Comment by ronaldtse** [comment] 2022-08-04 17:19
@andrew2net is there a way to keep the link as an additional "access location"? For example, in ISO 690 we have the "Available at: ..." link, and this is just an additional link.

**Comment by andrew2net** [comment] 2022-08-04 17:25
@ronaldtse we can save the link as [TypedUri](https://github.com/relaton/relaton-models/blob/fee9ea8205756163a1d96de47f9b105dc701d8a0/grammars/biblio.rnc#L296) with type like `available_at`. Is it ok?

**Comment by ronaldtse** [comment] 2022-08-04 17:26
@andrew2net great, then let's call this type `latest` because it is the latest draft available. Any objections @opoudjis ?

**Comment by opoudjis** [comment] 2022-08-05 02:47
No objection to the URI, but I'd prefer "current". The emphasis should not be on recency, but on validity.

I'd like to point out to @strogonoff though that unversioned and versioned descriptions of bibliographic items are a problem we have already had to deal with for ISO, and any attempt to come up with a different solution is to be rejected. Unversioned bibitems have no date, and they point to the latest version as `relation[@type = 'instance']/bibitem` (i.e the linked bibitem is an instance of the parent item). We haven't differentiated the current instance from older instances to date, because their status does that for us: only one instance (versioned bibitem) is going to have a status of current. But if you insist on doing so, `<relation type="instance"><description>current</description><bibitem>...</bibitem></relation>`.

**Comment by ronaldtse** [comment] 2022-08-05 07:23
"Current" is fine. I'm not sure if the Editor's Draft has any bearing of "validity", though. It seems to be more like "this draft is being developed here".

**Comment by andrew2net** [comment] 2022-08-06 13:12
@strogonoff  @ronaldtse now:
- The latest version is relation type [instance](https://github.com/relaton/relaton-data-w3c/blob/7257f8c730fc5d89dbdf300c00f881b641881ae0/data/2dcontext.yaml#L33-L42).
- The [document](https://github.com/relaton/relaton-data-w3c/blob/7257f8c730fc5d89dbdf300c00f881b641881ae0/data/design-principles.yaml#L46) has `doctype: groupNote` instead `Recommendation`.
- Editor's draft relation now is [link](https://github.com/relaton/relaton-data-w3c/blob/7257f8c730fc5d89dbdf300c00f881b641881ae0/data/note-design-principles-20211216.yaml#L9-L10)

Is it correct?

**Comment by ronaldtse** [comment] 2022-08-11 04:11
Looks great to me. 

@opoudjis and @strogonoff thoughts?

**Comment by andrew2net** [comment] 2023-04-08 01:00
@ronaldtse can we close this issue?

**Comment by opoudjis** [comment] 2023-06-07 18:04
No objection from me to closing this. @ronaldtse ?

**Closed** 2023-06-08 00:41 UTC
Labels: bug
